@startuml

用户 --> 系统服务端 : 输入账号与密码
系统服务端 -> 密码签名模块 : MD5哈希算法
密码签名模块 -> 系统服务端 : 返回哈希值
系统服务端 -> 数据库 : 条件查询（账号与哈希值）
系统服务端 <- 数据库 : 返回查询结果
alt 查询结果为Null
    系统服务端 --> 用户 : 登录失败提示
else 查询结果不为Null
    系统服务端 -> JWT算法 : 生成Token
    系统服务端 --> 用户 : 返回Token与用户信息，提示登录成功
end
@enduml
