@startuml

actor 系统管理员 as Admin
participant 服务端 as Server
database 数据库 as DB

==脚本上传==

Admin -> Server : 输入脚本名字、介绍，上传Python脚本，访问接口upload_script
Server -> Server : 保存脚本文件，将地址与信息存入数据库脚本表中
Server --> Admin : 返回上传成功信息

==脚本查询==

Admin -> Server : 访问脚本列表接口，获取脚本列表
Server -> DB : 查询脚本信息
Server --> Admin : 返回脚本列表
Admin -> Server : 选择需要更新或删除的脚本
Admin --> Server : 发送更新或删除请求

==脚本更新==

Admin -> Server : 选择需要更新的脚本，上传新的脚本文件，访问接口update_script
Server -> Server : 保存脚本文件，更新脚本信息
Server -> DB : 执行更新语句，将新的地址和信息存入数据库脚本表中
Server --> Admin : 返回更新成功信息

==脚本删除==

Admin -> Server : 选择需要删除的脚本，访问删除接口
Server -> DB : 执行删除语句，删除脚本
Server --> Admin : 返回删除成功信息

@enduml
